config/routes.rb
Rails.application.routes.draw do
  
  get 'plantas' => 'planta#index'
  get 'variedades' => 'variedad#index'
  get 'inmuebles/:id' => 'inmueble#index' , as: :inmuebles
  get 'fincaraiz' => 'finca_raiz#index'
  get '/variedadplantas/:id', to: 'variedad#show'
  get '/planta/:id', to: 'planta#show', as: :planta
  root to: 'inicio#index'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/inmueble.rb
class Inmueble < ActiveRecord::Base
end

app/models/planta.rb
class Planta < ActiveRecord::Base
end

app/models/tipo_de_inmueble.rb
class TipoDeInmueble < ActiveRecord::Base
	has_many :inmuebles
end

app/models/variedad.rb
class Variedad < ActiveRecord::Base
	has_many :plantas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/finca_raiz_controller.rb
class FincaRaizController < ApplicationController
	def index
		@tipos_de_inmueble = TipoDeInmueble.all
	end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
	def index
		
	end
end

app/controllers/inmueble_controller.rb
class InmuebleController < ApplicationController
	def index		
		@tipo_de_inmueble = TipoDeInmueble.find(params[:id])
		@inmuebles = @tipo_de_inmueble.inmuebles.all
	end
end

app/controllers/planta_controller.rb
class PlantaController < ApplicationController
	def index
		@plantas = Planta.all
	end
	def show
	end
end

app/controllers/variedad_controller.rb
class VariedadController < ApplicationController
	def index
		@variedades = Variedad.all
	end
	def show		
		@variedad = Variedad.find(params[:id])
		@plantas = @variedad.plantas.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finca_raiz_helper.rb
module FincaRaizHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/inmueble_helper.rb
module InmuebleHelper
end

app/helpers/planta_helper.rb
module PlantaHelper
end

app/helpers/variedad_helper.rb
module VariedadHelper
end

app/views/finca_raiz/index.html.erb
<% content_for(:titulo) do %>Finca Raiz<% end %>
<% @tipos_de_inmueble.each do |tipo_de_inmueble| %>
	<%= link_to("#{tipo_de_inmueble.nombre}", inmuebles_path(id: tipo_de_inmueble.id)) %>
<% end %>

app/views/inicio/index.html.erb
<% content_for(:titulo) do %>Interplantas<% end %>
<ul>
	<li><%= link_to "Inicio", root_path %></li>
	<li><%= link_to "Vivero", variedades_path %></li>
	<li><%= link_to "fincaraiz", fincaraiz_path %></li>
</ul>

app/views/inmueble/index.html.erb
<% content_for(:titulo) do %><% @tipo_de_inmueble.nombre %><% end %>

<% @inmuebles.each do |inmueble| %>
	<%= inmueble.nombre %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:titulo) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/planta/index.html.erb
<% content_for(:titulo) do %>Vivero<% end %>
Cayeno (Hibiscus)

app/views/planta/show.html.erb
<% content_for(:titulo) do %>Vivero<% end %>
Cayeno Rosado

app/views/variedad/index.html.erb
<% content_for(:titulo) do %>Vivero<% end %>
<% @variedades.each do |variedad| %>
	<%= link_to "#{variedad.nombre}", controller: "variedad", action: "show", id: variedad.id %>
<% end %>

app/views/variedad/show.html.erb
<% content_for(:titulo) do %>Vivero<% end %>
<% @plantas.each do |planta| %>
	<%= link_to "#{planta.nombre}", planta_url(nombre: planta.nombre) %>
<% end %>